### ISSUE TITLE
can't use it on windows cause buffertools dependency

### ISSUE THREAD

**Issue by 1000i100** [dodo/node-bufferstream#9]
there is no binary and there is compilation issue on windows when installing buffertools.
does buffertools is absolutely needed for buferstream or bufferjs or new 0.8+ features like native Buffer.concat could do the job without buffertools dependency ?
(It's what emailjs have done)
https://github.com/eleith/emailjs/pull/36

**Comment by dodo** [comment]
sorry, there is still no native Buffer.indexOf.
show me a js version and i'll use it.

**Comment by 1000i100** [comment]
I've not tested it but https://github.com/coolaj86/node-bufferjs provide Buffer.indexOf if you want make a try.

**Comment by dodo** [comment]
ok, i'm using bufferjs now. but buffertools can be still used optionally.
